const coins = [
    { name: "Ethereum",
        symbol: "ETH", },
    { name: "Litecoin",
        symbol: "LTC", },
    { name: "Binance Coin",
        symbol: "BNB", },
    { name: "NEO",
        symbol: "NEO", },
    { name: "Bitcoin Cash",
        symbol: "BCC", },
    { name: "Gas",
        symbol: "GAS", },
    { name: "HSR",
        symbol: "HyperCash", },
    { name: "MCO",
        symbol: "Monaco", },
    { name: "WTC",
        symbol: "Waltonchain", },
    { name: "Loopring",
        symbol: "LRC", },
    { name: "Quantum",
        symbol: "QTUM", },
    { name: "YOYOW",
        symbol: "YOYO", },
    { name: "OmiseGo",
        symbol: "OMG", },
    { name: "0x",
        symbol: "ZRX", },
    { name: "Stratis",
        symbol: "STRAT", },
    { name: "SingularDTV",
        symbol: "SNGLS", },
    { name: "Ethos",
        symbol: "BQX", },
    { name: "Kyber Network",
        symbol: "KNC", },
    { name: "Funfair",
        symbol: "FUN", },
    { name: "SONM",
        symbol: "SNM", },
    { name: "Iota",
        symbol: "IOTA", },
    { name: "ChainLink",
        symbol: "LINK", },
    { name: "Verge",
        symbol: "XVG", },
    { name: "Salt",
        symbol: "SALT", },
    { name: "Moeda Loyalty Points",
        symbol: "MDA", },
    { name: "Metal",
        symbol: "MTL", },
    { name: "Substratum",
        symbol: "SUB", },
    { name: "Eos",
        symbol: "EOS", },
    { name: "Status",
        symbol: "SNT", },
    { name: "Ethereum Classic",
        symbol: "ETC", },
    { name: "Mithril",
        symbol: "MTH", },
    { name: "Enigma",
        symbol: "ENG", },
    { name: "District 0x",
        symbol: "DNT", },
    { name: "Zcash",
        symbol: "ZEC", },
    { name: "Bancor",
        symbol: "BNT", },
    { name: "Airswap",
        symbol: "AST", },
    { name: "Dash",
        symbol: "DASH", },
    { name: "OAX",
        symbol: "OAX", },
    { name: "Iconomi",
        symbol: "ICN", },
    { name: "Bitcoin Gold",
        symbol: "BTG", },
    { name: "Everex",
        symbol: "EVX", },
    { name: "Request Network",
        symbol: "REQ", },
    { name: "Viberate",
        symbol: "VIB", },
    { name: "Tron",
        symbol: "TRX", },
    { name: "Power Ledger",
        symbol: "POWR", },
    { name: "Ark",
        symbol: "ARK", },
    { name: "Ripple",
        symbol: "XRP", },
    { name: "Enjin",
        symbol: "ENJ", },
    { name: "Storj",
        symbol: "STROJ", },
    { name: "VeChain",
        symbol: "VEN", },
    { name: "Komodo",
        symbol: "KMD", },
    { name: "Ripio Credit Network",
        symbol: "RCN", },
    { name: "Nuls",
        symbol: "NULS", },
    { name: "Raiden Network",
        symbol: "RDN", },
    { name: "Monero",
        symbol: "XMR", },
    { name: "Agrello",
        symbol: "DLT", },
    { name: "Ambrosus",
        symbol: "AMB", },
    { name: "Basic Attention Token",
        symbol: "BAT", },
    { name: "Bitcoin Private",
        symbol: "BCPT", },
    { name: "Aeron",
        symbol: "ARN", },
    { name: "Genesis Vision",
        symbol: "GVT", },
    { name: "Blox",
        symbol: "CDT", },
    { name: "GXChain",
        symbol: "GXS", },
    { name: "Po.et",
        symbol: "POE", },
    { name: "Quantstamp",
        symbol: "QSP", },
    { name: "BitShares",
        symbol: "BTS", },
    { name: "ZCoin",
        symbol: "XCZ", },
    { name: "Lisk",
        symbol: "LSK", },
    { name: "Tierion",
        symbol: "TNT", },
    { name: "Etherparty",
        symbol: "FUEL", },
    { name: "Decentraland",
        symbol: "MANA", },
    { name: "Bitcoin Diamond",
        symbol: "BCD", },
    { name: "Ethereum",
        symbol: "ETH", },
    { name: "DigixDAO",
        symbol: "DGD", },
    { name: "Ethereum",
        symbol: "ETH", },
];

export default coins;